# The MIT License (MIT)
#
# Copyright (c) 2021-2025 Yegor Bugayenko
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# See https://oss-review-toolkit.org/ort/docs/configuration/ort-yml for file specification
---
curations:
  packages:
  - id: "Maven:edu.berkeley.cs.jqf:jqf-fuzz:2.0"
    curations:
      comment: |-
        Set the VCS path of the module inside the multi-module repository.
      vcs:
        path: "fuzz"
  - id: "Maven:edu.berkeley.cs.jqf:jqf-fuzz:2.0"
    curations:
      comment: |-
        Mapped based on https://github.com/rohanpadhye/JQF/blob/jqf-2.0/LICENSE.
      declared_license_mapping:
        "FreeBSD License": "BSD-2-Clause"
  - id: "Maven:edu.berkeley.cs.jqf:jqf-instrument:2.0"
    curations:
      comment: |-
        "Mapped based on https://github.com/rohanpadhye/JQF/blob/jqf-2.0/LICENSE."
      declared_license_mapping:
        "FreeBSD License": "BSD-2-Clause"
  - id: "Maven:edu.berkeley.cs.jqf:jqf-instrument:2.0"
    curations:
      comment: |-
        Set the VCS path of the module inside the multi-module repository.
      vcs:
        path: "instrument"
license_choices:
  package_license_choices:
  - package_id: "Maven:org.glassfish:javax.json:1.1.4"
    license_choices:
    - given: CDDL-1.1 OR GPL-2.0-only
      choice: CDDL-1.1
  - package_id: "Maven:javax.json:javax.json-api:1.1.4"
    license_choices:
      - given: CDDL-1.1 OR GPL-2.0-only
        choice: CDDL-1.1
